---
- name: "j163.009.java7_iim_credentials.yaml{{':'}} imcl saveCredential{{':'}} IIM credentials required for access to IBM hosted IIM repository."
  hosts: all
  gather_facts: no
  vars:
    imutilsc: "{{ '/'.join( (ibm.fs_root, 
                             iim.dir, 
                             iim.install_loc, 
                             'eclipse/tools/imutilsc', ) ) }}"
  tasks:
  - import_role:
      name: common

  - name: Create "master password file" to provide a passphrase. (Ansible Vault candidate.)
    become: yes
    become_user: "{{ iim.usr }}"
    copy:
      dest: "{{ '/'.join(('/home', iim.usr, iim.ibmid.file)) }}"
      content: replace_this_string
      mode: 0600

  - name: "{{ imutilsc }} saveCredential."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv: 
      - "{{ imutilsc }}"
      - 'saveCredential'
      - '-url'
      - http://www.ibm.com/software/repositorymanager/com.ibm.cic.packagingUtility/repository.config
      - '-userName'
      - '{{ iim.ibmid.email }}'
      - '-userPassword'
      - "{{ iim.ibmid.pw }}"
      - '-secureStorageFile'
      - "{{ '/'.join(('/home', iim.usr, iim.secureStorageFile)) }}"
      - '-masterPasswordFile' 
      - "{{ '/'.join(('/home', iim.usr, iim.ibmid.file)) }}"

    register: rgstr_saveCredential
  - debug:
      var: rgstr_saveCredential.stdout
      verbosity: 1
...