---
- name: "j163.011.java7_FP08_IBM_hosted_repository_install.yaml{{':'}} imcl install{{':'}} IBM Java7 Fix Pack 08, IBM hosted IIM repository."
  hosts: all
  gather_facts: no
  vars:
    imcl: "{{ '/'.join( (ibm.fs_root, 
                         iim.dir, 
                         iim.install_loc, 
                         'eclipse/tools/imcl', ) ) }}"
  tasks:
  - import_role:
      name: common

  - name: "{{ imcl }}{{':'}} install maintenance for unit-test to dev-test November 2014 levels; from IBM hosted IIM repository."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - "{{ imcl }}"
      - install
      - com.ibm.websphere.IBMJAVA.v70_7.0.8000.20141118_1016
      - "-repositories"
      # https://www.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.installation.nd.doc/ae/cins_repositories.html
      - http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IBMJAVA.v70
      - "-installationDirectory"
      - "{{ '/'.join((ibm.fs_root, nd.dir_ND)) }}"
      - "-secureStorageFile"
      - "{{ '/'.join(('/home', iim.usr, iim.secureStorageFile)) }}"
      - "-masterPasswordFile"
      - "{{ '/'.join(('/home', iim.usr, iim.ibmid.file)) }}"
      - "-preferences" 
      - "{{ ('com.ibm.cic.common.core.preferences.keepFetchedFiles=false',
             'com.ibm.cic.common.core.preferences.preserveDownloadedArtifacts=false',
             'com.ibm.cic.common.core.preferences.searchForUpdates=false', ) | join(',') }}"
      - '-acceptLicense'
      - '-showProgress'
      # - '-showVerboseProgress'

    register: rgstr_mnt_updt
    tags: mnt_updt
  - name: "cmd{{':'}} \"rgstr_mnt_updt\" register of previous task."
    debug:
      var: rgstr_mnt_updt.cmd
      verbosity: 1
    tags: mnt_updt
  - name: "stdout{{':'}} \"rgstr_mnt_updt\" register of previous task."
    debug:
      var: rgstr_mnt_updt.stdout
      verbosity: 1
    tags: mnt_updt

  - name: "Validate \"imcl\" install action with \"listInstalledPackages\"."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - "{{ imcl }}"
      - listInstalledPackages
      - '-verbose'
      - '-showProgress'
      # - '-showVerboseProgress'

    register: rgstr_imcl_lstInstllPkg
    tags:
    - lstInstllPkg
  - name: "cmd{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.cmd
      verbosity: 1
    tags:
    - lstInstllPkg
  - name: "stdout{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.stdout
      verbosity: 1
    tags:
    - lstInstllPkg

  - name: "Validate ND install{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    register: rgstr_verInfo
    tags:
    - verInfo
  - name: "stdout{{':'}} \"rgstr_verInfo\" register of previous task."
    debug:
      var: rgstr_verInfo.stdout
      verbosity: 1
    tags:
    - verInfo

  - name: "Report \"java -version\"{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'java_1.7_64/bin/java -version', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'java_1.7_64/bin/java -version', ) | join('/') }}"
    register: rgstr_javaVer
    tags:
    - javaVer
  - name: "stderr{{':'}} \"rgstr_javaVer\" register of previous task."
    debug:
      var: rgstr_javaVer.stderr
      verbosity: 1
    tags:
    - javaVer
...