---
- name: "j163.007.java7_install.yaml{{':'}} WAS 8.5.5 installs Java 1.6.0 by default, now install IBM Java 7 SDK from ESD repository."
  hosts: all
  gather_facts: no
  vars:
    imcl: "{{ '/'.join( (ibm.fs_root, 
                         iim.dir, 
                         iim.install_loc, 
                         'eclipse/tools/imcl', ) ) }}"
  tasks:
  - import_role:
      name: common

  - name: "{{ imcl }}{{':'}} install \"com.ibm.websphere.IBMJAVA.v70_7.0.4001.20130510_2103\" from IIM ESD SAC repository."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - '{{ imcl }}'
      - install
      - com.ibm.websphere.IBMJAVA.v70_7.0.4001.20130510_2103
      - '-repositories'
      - /opt/shbx/esd_PPA_SAC/was855_java7
      - '-installationDirectory'
      - "{{ '/'.join((ibm.fs_root, nd.dir_ND)) }}"
      - '-preferences' 
      - "{{ ('com.ibm.cic.common.core.preferences.keepFetchedFiles=false',
             'com.ibm.cic.common.core.preferences.preserveDownloadedArtifacts=false',
             'com.ibm.cic.common.core.preferences.searchForUpdates=false', ) | join(',') }}"
      - '-acceptLicense'
      - '-showProgress'
      # - '-showVerboseProgress'
    register: rgstr_java7_instl
    tags: java7_instl
  - name: "cmd{{':'}} \"rgstr_java7_instl\" register of previous task."
    debug:
      var: rgstr_java7_instl.cmd
      verbosity: 1
    tags: java7_instl
  - name: "stdout{{':'}} \"rgstr_java7_instl\" register of previous task."
    debug:
      var: rgstr_java7_instl.stdout
      verbosity: 1
    tags: java7_instl

  - name: "Validate \"imcl\" install action with \"listInstalledPackages\"."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - "{{ imcl }}"
      - listInstalledPackages
      - '-verbose'
    register: rgstr_imcl_lstInstllPkg
    tags:
    - lstInstllPkg
  - name: "cmd{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.cmd
      verbosity: 1
    tags:
    - lstInstllPkg
  - name: "stdout{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.stdout
      verbosity: 1
    tags:
    - lstInstllPkg

  - name: "Validate install{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    register: rgstr_verInfo
    tags:
    - verInfo
  - name: "stdout{{':'}} \"rgstr_verInfo\" register of previous task."
    debug:
      verbosity: 1
      var: rgstr_verInfo.stdout
    tags:
    - verInfo

  - name: "Report \"java -version\"{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'java_1.7_64/bin/java -version', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'java_1.7_64/bin/java -version', ) | join('/') }}"
    register: rgstr_javaVer
    tags:
    - javaVer
  - name: "stderr{{':'}} \"rgstr_javaVer\" register of previous task."
    debug:
      var: rgstr_javaVer.stderr
      verbosity: 1
    tags:
    - javaVer
...