---
- name: "imcl install{{':'}} CRM2SML IBM WebSphere Application Server V8.5.5 Base from ESD, PPA, repository."
  hosts: all
  gather_facts: no
  vars:
    imcl: "{{ '/'.join( (ibm.fs_root, 
                         iim.dir, 
                         iim.install_loc, 
                         'eclipse/tools/imcl', ) ) }}"
  tasks:
  - import_role:
      name: common

  - name: "{{ imcl }}{{':'}} install IBM WebSphere Application Server V8.5.5"
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - "{{ imcl }}"
      - "install"
      - com.ibm.websphere.BASE.v85_8.5.5000.20130514_1044,ejbdeploy,embeddablecontainer,com.ibm.sdk.6_64bit,samples
      - "-repositories"
      - /opt/shbx/esd_PPA_SAC/was855_base
      - "-installationDirectory"
      - "{{ '/'.join((ibm.fs_root, nd.fs_leaf)) }}"
      - "-preferences" 
      - "{{ ('com.ibm.cic.common.core.preferences.keepFetchedFiles=false',
             'com.ibm.cic.common.core.preferences.preserveDownloadedArtifacts=false',
             'com.ibm.cic.common.core.preferences.searchForUpdates=false', ) | join(',') }}"
      - "-acceptLicense"
      - "-showProgress"
      # - "-showVerboseProgress"
    register: rgstr_nd_instl
    tags: nd_install
  - name: "cmd{{':'}} \"rgstr_nd_instl\" register of previous task."
    debug:
      var: rgstr_nd_instl.cmd
      verbosity: 1
    tags: nd_install
  - name: "stdout{{':'}} \"rgstr_nd_instl\" register of previous task."
    debug:
      var: rgstr_nd_instl.stdout
      verbosity: 1
    tags: nd_install

  - name: "Validate \"imcl\" install action with \"listInstalledPackages\"."
    become: yes
    become_user: "{{ iim.usr }}"
    command:
      argv:
      - "{{ imcl }}"
      - listInstalledPackages
      - '-verbose'
    register: rgstr_imcl_lstInstllPkg
    tags:
    - lstInstllPkg
  - name: "cmd{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.cmd
      verbosity: 1
    tags:
    - lstInstllPkg
  - name: "stdout{{':'}} \"rgstr_imcl_lstInstllPkg\" register of previous task."
    debug:
      var: rgstr_imcl_lstInstllPkg.stdout
      verbosity: 1
    tags:
    - lstInstllPkg

  - name: "Validate ND install{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'bin/versionInfo.sh', ) | join('/') }}"
    register: rgstr_verInfo
    tags:
    - verInfo
  - name: "stdout{{':'}} \"rgstr_verInfo\" register of previous task."
    debug:
      var: rgstr_verInfo.stdout
      verbosity: 1
    tags:
    - verInfo

  - name: "Report \"java -version\"{{':'}} {{ ( ibm.fs_root, nd.dir_ND,'java/bin/java -version', ) | join('/') }}"
    command: "{{ ( ibm.fs_root, nd.dir_ND,'java/bin/java -version', ) | join('/') }}"
    register: rgstr_javaVer
    tags:
    - javaVer
  - name: "stderr{{':'}} \"rgstr_javaVer\" register of previous task."
    debug:
      var: rgstr_javaVer.stderr
      verbosity: 1
    tags:
    - javaVer
...